### ISSUE TITLE
Reasons for manual reloadComponentData

### ISSUE THREAD

**Issue by Yomguithereal** [mistadikay/doob#1]
Hello @mistadikay. 
One thing I do not understand about the `DataWatcher` decorator is the obligation to manually trigger `reloadComponentData`. Why not trigger it automatically as in your example in the `componentWillReceiveProps` hook?

**Comment by mistadikay** [comment]
Hi @Yomguithereal. Thanks for the feedback!

Yeah, actually we were thinking about that but hesitated because not every data dependency contains props and reloading data every time would be a slight overhead. But the more we work with this manual `reloadComponentData`, the more we think that maybe reloading it automatically wouldn't be that bad. So yes, I think we'll automate it in one of the nearest releases.

**Comment by mistadikay** [comment]
fixed in https://github.com/mistadikay/doob/commit/0c218b174c42c06ba438ef31c4431cc0cb82fadf
